/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_platform_OSFileSystem */

#ifndef _Included_com_ibm_platform_OSFileSystem
#define _Included_com_ibm_platform_OSFileSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_platform_OSFileSystem
 * Method:    fflushImpl
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_platform_OSFileSystem_fflushImpl
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_ibm_platform_OSFileSystem
 * Method:    seekImpl
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_platform_OSFileSystem_seekImpl
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_ibm_platform_OSFileSystem
 * Method:    readImpl
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_platform_OSFileSystem_readImpl
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_ibm_platform_OSFileSystem
 * Method:    writeImpl
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ibm_platform_OSFileSystem_writeImpl
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ibm_platform_OSFileSystem
 * Method:    closeImpl
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_platform_OSFileSystem_closeImpl
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ibm_platform_OSFileSystem
 * Method:    truncateImpl
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_platform_OSFileSystem_truncateImpl
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ibm_platform_OSFileSystem
 * Method:    openImpl
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_platform_OSFileSystem_openImpl
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif

