/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_File */

#ifndef _Included_java_io_File
#define _Included_java_io_File
#ifdef __cplusplus
extern "C" {
#endif
#undef java_io_File_serialVersionUID
#define java_io_File_serialVersionUID 301077366599181567i64
/*
 * Class:     java_io_File
 * Method:    oneTimeInitialization
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_File_oneTimeInitialization
  (JNIEnv *, jclass);

/*
 * Class:     java_io_File
 * Method:    rootsImpl
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_java_io_File_rootsImpl
  (JNIEnv *, jclass);

/*
 * Class:     java_io_File
 * Method:    isCaseSensitiveImpl
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_isCaseSensitiveImpl
  (JNIEnv *, jclass);

/*
 * Class:     java_io_File
 * Method:    deleteDirImpl
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_deleteDirImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    deleteFileImpl
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_deleteFileImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    existsImpl
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_existsImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    getCanonImpl
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_io_File_getCanonImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    isAbsoluteImpl
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_isAbsoluteImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    isDirectoryImpl
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_isDirectoryImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    isFileImpl
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_isFileImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    isHiddenImpl
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_isHiddenImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    isReadOnlyImpl
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_isReadOnlyImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    isWriteOnlyImpl
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_isWriteOnlyImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    getLinkImpl
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_io_File_getLinkImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    lastModifiedImpl
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_java_io_File_lastModifiedImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    setLastModifiedImpl
 * Signature: ([BJ)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_setLastModifiedImpl
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     java_io_File
 * Method:    setReadOnlyImpl
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_setReadOnlyImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    lengthImpl
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_java_io_File_lengthImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    listImpl
 * Signature: ([B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_java_io_File_listImpl
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    mkdirImpl
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_mkdirImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    newFileImpl
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_java_io_File_newFileImpl
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    properPathImpl
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_java_io_File_properPathImpl
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     java_io_File
 * Method:    renameToImpl
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_renameToImpl
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif

